
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSCHAR DATATYPE DIVIDE LPAREN MINUS NUMBER PLUS PRINT RPAREN STR TIMES\n    expression : expression PLUS expression\n               | expression MINUS expression\n               | expression TIMES expression\n               | expression DIVIDE expression\n\n    expression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : NUMBERexpression : STRexpression : CHAR\n    datatype : DATATYPE expression\n    expression : PRINT STR\n                  | PRINT CHAR\n                  | PRINT NUMBER\n                  | PRINT expression\n    '
    
_lr_action_items = {'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[2,9,2,2,-7,-8,-9,2,2,2,2,2,-5,9,-8,-9,-7,9,-1,-2,-3,-4,-6,]),'LPAREN':([0,2,3,7,8,9,10,11,],[3,3,3,3,3,3,3,3,]),'NUMBER':([0,2,3,7,8,9,10,11,],[4,4,4,16,4,4,4,4,]),'STR':([0,2,3,7,8,9,10,11,],[5,5,5,14,5,5,5,5,]),'CHAR':([0,2,3,7,8,9,10,11,],[6,6,6,15,6,6,6,6,]),'PRINT':([0,2,3,7,8,9,10,11,],[7,7,7,7,7,7,7,7,]),'$end':([1,4,5,6,12,14,15,16,17,18,19,20,21,22,],[0,-7,-8,-9,-5,-8,-9,-7,-14,-1,-2,-3,-4,-6,]),'PLUS':([1,4,5,6,12,13,14,15,16,17,18,19,20,21,22,],[8,-7,-8,-9,-5,8,-8,-9,-7,8,-1,-2,-3,-4,-6,]),'TIMES':([1,4,5,6,12,13,14,15,16,17,18,19,20,21,22,],[10,-7,-8,-9,-5,10,-8,-9,-7,10,10,10,-3,-4,-6,]),'DIVIDE':([1,4,5,6,12,13,14,15,16,17,18,19,20,21,22,],[11,-7,-8,-9,-5,11,-8,-9,-7,11,11,11,-3,-4,-6,]),'RPAREN':([4,5,6,12,13,14,15,16,17,18,19,20,21,22,],[-7,-8,-9,-5,22,-8,-9,-7,-14,-1,-2,-3,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,7,8,9,10,11,],[1,12,13,17,18,19,20,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression','parser.py',52),
  ('expression -> expression MINUS expression','expression',3,'p_expression','parser.py',53),
  ('expression -> expression TIMES expression','expression',3,'p_expression','parser.py',54),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','parser.py',55),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','parser.py',68),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',72),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',76),
  ('expression -> STR','expression',1,'p_expression_str','parser.py',80),
  ('expression -> CHAR','expression',1,'p_expression_char','parser.py',84),
  ('datatype -> DATATYPE expression','datatype',2,'p_datatype','parser.py',89),
  ('expression -> PRINT STR','expression',2,'p_print','parser.py',97),
  ('expression -> PRINT CHAR','expression',2,'p_print','parser.py',98),
  ('expression -> PRINT NUMBER','expression',2,'p_print','parser.py',99),
  ('expression -> PRINT expression','expression',2,'p_print','parser.py',100),
]
